<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.1 Performing the multivariate regression | _main.utf8.md</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="5.1 Performing the multivariate regression | _main.utf8.md" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.1 Performing the multivariate regression | _main.utf8.md" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="improving-our-analysis.html"/>
<link rel="next" href="conclusion.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i><b>2</b> Preface</a><ul>
<li class="chapter" data-level="2.0.1" data-path="preface.html"><a href="preface.html#the-original-story"><i class="fa fa-check"></i><b>2.0.1</b> The original story</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-data.html"><a href="the-data.html"><i class="fa fa-check"></i><b>3</b> The Data</a><ul>
<li class="chapter" data-level="3.1" data-path="turning-our-question-into-measureables.html"><a href="turning-our-question-into-measureables.html"><i class="fa fa-check"></i><b>3.1</b> Turning our question into measureables</a></li>
<li class="chapter" data-level="3.2" data-path="data-life-expectancy.html"><a href="data-life-expectancy.html"><i class="fa fa-check"></i><b>3.2</b> Data: Life expectancy</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-life-expectancy.html"><a href="data-life-expectancy.html#the-data-dictionary"><i class="fa fa-check"></i><b>3.2.1</b> The data dictionary</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-unemployment.html"><a href="data-unemployment.html"><i class="fa fa-check"></i><b>3.3</b> Data: Unemployment</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-unemployment.html"><a href="data-unemployment.html#picking-a-data-source-editorial-choice"><i class="fa fa-check"></i><b>3.3.1</b> Picking a data source (editorial choice)</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-unemployment.html"><a href="data-unemployment.html#picking-a-survey-year"><i class="fa fa-check"></i><b>3.3.2</b> Picking a survey year</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-unemployment.html"><a href="data-unemployment.html#picking-an-unemployment-table"><i class="fa fa-check"></i><b>3.3.3</b> Picking an unemployment table</a></li>
<li class="chapter" data-level="3.3.4" data-path="data-unemployment.html"><a href="data-unemployment.html#the-data-dictionary-1"><i class="fa fa-check"></i><b>3.3.4</b> The data dictionary</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-demographics.html"><a href="data-demographics.html"><i class="fa fa-check"></i><b>3.4</b> Data: Demographics</a></li>
<li class="chapter" data-level="3.5" data-path="combining-our-datasets.html"><a href="combining-our-datasets.html"><i class="fa fa-check"></i><b>3.5</b> Combining our datasets</a><ul>
<li class="chapter" data-level="3.5.1" data-path="combining-our-datasets.html"><a href="combining-our-datasets.html#reading-in-life-expectancy"><i class="fa fa-check"></i><b>3.5.1</b> Reading in life expectancy</a></li>
<li class="chapter" data-level="3.5.2" data-path="combining-our-datasets.html"><a href="combining-our-datasets.html#reading-in-unemployment"><i class="fa fa-check"></i><b>3.5.2</b> Reading in unemployment</a></li>
<li class="chapter" data-level="3.5.3" data-path="combining-our-datasets.html"><a href="combining-our-datasets.html#final-joining"><i class="fa fa-check"></i><b>3.5.3</b> Final joining</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analyzing-our-data.html"><a href="analyzing-our-data.html"><i class="fa fa-check"></i><b>4</b> Analyzing our data</a><ul>
<li class="chapter" data-level="4.1" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>4.1</b> Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="interpreting-coefficients.html"><a href="interpreting-coefficients.html"><i class="fa fa-check"></i><b>4.2</b> Interpreting coefficients</a><ul>
<li class="chapter" data-level="4.2.1" data-path="interpreting-coefficients.html"><a href="interpreting-coefficients.html#understanding-const"><i class="fa fa-check"></i><b>4.2.1</b> Understanding const</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="improving-our-analysis.html"><a href="improving-our-analysis.html"><i class="fa fa-check"></i><b>5</b> Improving our analysis</a><ul>
<li class="chapter" data-level="5.0.1" data-path="improving-our-analysis.html"><a href="improving-our-analysis.html#reading-in-and-processing-our-data"><i class="fa fa-check"></i><b>5.0.1</b> Reading in and processing our data</a></li>
<li class="chapter" data-level="5.1" data-path="performing-the-multivariate-regression.html"><a href="performing-the-multivariate-regression.html"><i class="fa fa-check"></i><b>5.1</b> Performing the multivariate regression</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="performing-the-multivariate-regression" class="section level2">
<h2><span class="header-section-number">5.1</span> Performing the multivariate regression</h2>
<p>Remember how linear regression hates missing data? Nothing’s changed since last chapter! Before we perform our regression, we’ll need to drop any rows missing data, whether it’s race data, unemployment data, poverty data, or anything else.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb31-1"><a href="performing-the-multivariate-regression.html#cb31-1"></a><span class="co"># Make note of our original dataframe size</span></span>
<span id="cb31-2"><a href="performing-the-multivariate-regression.html#cb31-2"></a>df.shape</span></code></pre></div>
<pre><code>## (65662, 10)</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb33-1"><a href="performing-the-multivariate-regression.html#cb33-1"></a><span class="co"># Drop rows with missing data, compare size</span></span>
<span id="cb33-2"><a href="performing-the-multivariate-regression.html#cb33-2"></a>df <span class="op">=</span> df.dropna()</span>
<span id="cb33-3"><a href="performing-the-multivariate-regression.html#cb33-3"></a>df.shape</span></code></pre></div>
<pre><code>## (65656, 10)</code></pre>
<p>Now we can perform our regression. This time instead of picking the columns we <em>want</em> to include in our regression, we’re just going to use <code>.drop</code> to remove the columns we <em>don’t</em> want to include in our regression. First we’ll look at it in isolation before we do the regression.</p>
<pre><code>X = df.drop(columns=[&#39;Tract ID&#39;, &#39;Geo_FIPS&#39;, &#39;life_expectancy&#39;])
X = sm.add_constant(X)
X.head()</code></pre>
<p>Make a note that we drop <code>life_expectancy</code> because it’s what we’re <em>predicting</em>. That makes it our <code>y</code> value, not our <code>X</code>. And even though we have all these extra columns this time, we still need to add the constant - linear regression would still want to make life expectancy zero if each of our columns were zero.</p>
<p>Now let’s do our multivariate regression.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb36-1"><a href="performing-the-multivariate-regression.html#cb36-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb36-2"><a href="performing-the-multivariate-regression.html#cb36-2"></a></span>
<span id="cb36-3"><a href="performing-the-multivariate-regression.html#cb36-3"></a>X <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">&#39;Tract ID&#39;</span>, <span class="st">&#39;Geo_FIPS&#39;</span>, <span class="st">&#39;life_expectancy&#39;</span>])</span>
<span id="cb36-4"><a href="performing-the-multivariate-regression.html#cb36-4"></a>y <span class="op">=</span> df[<span class="st">&#39;life_expectancy&#39;</span>]</span>
<span id="cb36-5"><a href="performing-the-multivariate-regression.html#cb36-5"></a></span>
<span id="cb36-6"><a href="performing-the-multivariate-regression.html#cb36-6"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb36-7"><a href="performing-the-multivariate-regression.html#cb36-7"></a>model <span class="op">=</span> sm.OLS(y,X)</span>
<span id="cb36-8"><a href="performing-the-multivariate-regression.html#cb36-8"></a></span>
<span id="cb36-9"><a href="performing-the-multivariate-regression.html#cb36-9"></a>results <span class="op">=</span> model.fit()</span>
<span id="cb36-10"><a href="performing-the-multivariate-regression.html#cb36-10"></a>results.summary()</span></code></pre></div>
<pre><code>## &lt;class &#39;statsmodels.iolib.summary.Summary&#39;&gt;
## &quot;&quot;&quot;
##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:        life_expectancy   R-squared:                       0.490
## Model:                            OLS   Adj. R-squared:                  0.490
## Method:                 Least Squares   F-statistic:                     8997.
## Date:                Sun, 01 Dec 2019   Prob (F-statistic):               0.00
## Time:                        21:17:54   Log-Likelihood:            -1.6208e+05
## No. Observations:               65656   AIC:                         3.242e+05
## Df Residuals:                   65648   BIC:                         3.243e+05
## Df Model:                           7                                         
## Covariance Type:            nonrobust                                         
## =======================================================================================
##                           coef    std err          t      P&gt;|t|      [0.025      0.975]
## ---------------------------------------------------------------------------------------
## const                  81.2365      0.122    665.628      0.000      80.997      81.476
## ritp_100_149_pct       -0.0596      0.003    -21.738      0.000      -0.065      -0.054
## black_pct              -0.0666      0.001    -56.960      0.000      -0.069      -0.064
## white_pct              -0.0386      0.001    -36.707      0.000      -0.041      -0.037
## hisp_pct                0.0131      0.001     10.298      0.000       0.011       0.016
## unemployed_pct         -0.1490      0.004    -33.408      0.000      -0.158      -0.140
## ea_less_than_hs_pct    -0.0862      0.002    -48.979      0.000      -0.090      -0.083
## median_income_10k       0.4825      0.006     83.217      0.000       0.471       0.494
## ==============================================================================
## Omnibus:                     2114.193   Durbin-Watson:                   1.520
## Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4788.035
## Skew:                           0.183   Prob(JB):                         0.00
## Kurtosis:                       4.271   Cond. No.                         790.
## ==============================================================================
## 
## Warnings:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## &quot;&quot;&quot;</code></pre>
<p>So many numbers! First, notice that the coefficient for <code>unemployed_pct</code> changed, changing from <code>-0.5214</code> to <code>-0.1490</code>. Now instead of losing half a year of life expectancy for a 1% increase in employment, you now lose about 0.15 years (a little under two months). Why did this happen?</p>
<p>When you do a multivariate regression, the regression is considering <em>all</em> of the factors at the same time. So now instead of thinking that unemployment is the <strong>only factor</strong> going into life expectancy, the regression is also weighing racial breakdown, income, and the other fields.</p>
<p>The new regression then discovered that some of the variation that the <em>first</em> regression said was due to unemployment is actually better explained by those other fields, so the coefficient for unemployment moved closer to zero.</p>
<p>Let’s take a look at all of the coefficients and see what we get.</p>
<p>|—|—|—|
|variable|coefficient|meaning|
|—|—|—|
|const|81.2365|If everything else is 0, life expectancy will be about 81 years|
|ritp_100_149_pct|-0.0596|For every 1 percentage point increase in people just above the poverty line, life expectancy goes down 0.06 years (~3 weeks)|
|black_pct|−0.0666|For every 1 percentage point increase in the black population, life expectancy decreases by 0.07 years (~3 and a half weeks)|
|white_pct|−0.0386|For every 1 percentage point increase in the white population, life expectancy goes down by 0.04 years (~2 weeks)|
|hisp_pct|0.0131|For every 1 percentage point increase in the hispanic population, life expectancy goes up 0.01 years (~4 days)|
|unemployed_pct|−0.1490|For every 1 percentage point increase in the unemployed population, life expectancy goes down 0.15 years (~8 weeks)|
|ea_less_than_hs_pct|−0.0862|For every 1 percentage point increase in people with less than high school education, life expectancy goes down 0.09 years (~4.5 weeks)|
|median_income_10k|0.4825|For every additional $10,000 in median income in an area, life expectancy increases 0.49 years (~6 months)|</p>
<p>So now we can find that line from the final published piece:</p>
<blockquote>
<p>An increase of 10 percentage points in the unemployment rate in a neighborhood translated to a loss of roughly a year and a half of life expectancy, the AP found. A neighborhood where more adults failed to graduate high school had shorter predicted longevity.</p>
</blockquote>
<p>While the regression was dealing with <strong>one percentage point</strong> of unemployment, saying “one percentage point loses roughly 8 weeks of life expectancy” is not nearly as impactful. If we multiply both sides by ten, we get something much more publishable: 1 percentage point becomes 10 percentage points, and −0.15 years becomes −1.5 years. And then we’re published in the AP!</p>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="improving-our-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 1
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

</body>

</html>
